name: Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      really_destroy:
        description: "Type YES to confirm! Please don't do this unless you know what you're doing!"
        required: true

env:
  AWS_REGION: eu-west-1
  TF_IN_AUTOMATION: "true"
  CLUSTER_NAME: eks-lab-cluster

jobs:
  destroy:
    environment: terraform
    if: github.event.inputs.really_destroy == 'YES'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install kubectl
        uses: azure/setup-kubectl@v4

      - uses: hashicorp/setup-terraform@v3
      - run: terraform init -input=false
      - run: terraform destroy -input=false -auto-approve