name: Terraform Apply

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AWS_REGION: eu-west-2
  TF_IN_AUTOMATION: "true"

jobs:
  tf:
    environment: terraform
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Verify S3 access
        run: aws s3 ls s3://boss-eks-lab-terraform-state/

      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init -input=false -reconfigure
        
      - run: terraform apply -input=false -auto-approve
